// FAKE DATA
export const books = [
  {
    id: 1,
    title: "The 7 Habits of Highly Effective People",
    url: "https://covers.openlibrary.org/b/id/9195831-M.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Grit",
    url: "https://covers.openlibrary.org/b/id/8899684-M.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Daring Greatly",
    url: "https://covers.openlibrary.org/b/id/9064278-M.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Talking to Strangers",
    url: "https://covers.openlibrary.org/b/id/8779682-M.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Subliminal",
    url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1369608255i/13058637.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "The Tipping Point",
    url: "https://covers.openlibrary.org/b/id/13894591-M.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Consistency Formula",
    url: "https://m.media-amazon.com/images/I/21-+BDOs5tL._SX322_BO1,204,203,200_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Radical Acceptance",
    url: "https://covers.openlibrary.org/b/id/10401407-M.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The Subtle Art of Not Giving a -",
    url: "https://covers.openlibrary.org/b/id/12833562-M.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];
